name: Docker image build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERTOKEN }}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ashutoshdas28/devopslab:v0.1 .

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push ashutoshdas28/devopslab:v0.1
